-- Prefer VectorChord's extension; load alternatives only if needed
DO $$
BEGIN
	BEGIN
		CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
	EXCEPTION WHEN others THEN
		PERFORM 1;
	END;
	BEGIN
		CREATE EXTENSION IF NOT EXISTS vectors;
	EXCEPTION WHEN others THEN
		PERFORM 1;
	END;
	BEGIN
		CREATE EXTENSION IF NOT EXISTS vector;
	EXCEPTION WHEN others THEN
		PERFORM 1;
	END;
END $$;
